apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ohikv3nkp-nodejs 
  janus-idp.io/tekton: ohikv3nkp-nodejs
  backstage.io/kubernetes-id: ohikv3nkp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ohikv3nkp-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml