apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ohikv3nkp-nodejs-gitops
  description: This is GitOps manifest for ohikv3nkp-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ohikv3nkp-nodejs
    backstage.io/kubernetes-id: ohikv3nkp-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ohikv3nkp-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ohikv3nkp-nodejs
