apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ohikv3nkp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ohikv3nkp-nodejs 
  name: ohikv3nkp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ohikv3nkp-nodejs 
